name: xw
description: Classes and Functions, meant to help other devs.
version: 2.7.3
# repository: https://github.com/manifestedmf/xw-dart

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0